run_type: julia
pixels: 800
frames: 61
seconds: 10
colormap: inferno
color_by: diverged
normalize_frame_colors: False
height: 3
center: 0.5
point_value_max: 10
steps: 50
zoom_start: 250
zoom_end: 500
shift: 0
power_start: 2.16
power_end: 2.16
param_degrees: 180
param_radius: 1
# do not set param for Mandelbrot sets, as it will be ignored
